name: snapshot
favicon: null
layout_spectrum: 0.97264
typography_spectrum: 0.31544
title: Snapshots
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e4e7'
    - '#cac0cb'
    - '#908492'
    - '#1f071f'
    - '#594659'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
